import React, { useContext } from 'react'
import { motion } from 'framer-motion';
import { navVariants } from '../../utils/motion';
import Grid from "@mui/material/Grid";

export default function PublishDiscriptionPromotionalSite() {


  return (
    <motion.nav variants={navVariants}
      initial="hidden"
      whileInView="show">
      <div className='container'>
          <div>
            <Grid container >
              <div className='discription' style={{ textAlign: `center`, color: `white`, fontSize: `28px`, fontFamily: 'Poppins' }}>BASIT VE KULLANIMI KOLAY BELGE OKUYUCU UYGULAMA MI ARIYORSUNUZ? PDF OKUYUCU TAM DA IHTIYACINIZ OLAN ŞEY! TELEFONUNUZDA TÜM PDF DOSYALARINI OTOMATIK TARAYABILIR, BULABILIR VE LISTELEYEBILIR, DOSYALARINIZI HIZLI AÇMA, OKUMA VE YÖNETME IMKANI SUNAR HEM DE TEK BIR YERDEN RAHATÇA.PDF OKUYUCU DOSYALARI ULTRA HIZLI OKUR HEM DE TÜM FORMATLARI, BELGELERI, MAKBUZLARI, FOTOĞRAFLARI, KARTVIZITLERI, BEYAZ TAHTALARI, VB. BU SADECE BIR OKUMA UYGULAMASI DEĞILDIR, AYRICA BU UYGULAMAYI PDF SAYFALARINDA METIN VURGULAMAK, NOT ALMAK, E-IMZA EKLEMEK, IŞARETLEME YAPMAK VE PDF DOSYALARINI BAŞKALARIYLA PAYLAŞMAK IÇIN DE KULLANABILIRSINIZ. İŞINIZI VE EĞITIMINIZI DESTEKLEMEK IÇIN BU ÜSTÜN OFIS UYGULAMASINI INDIRIN, PDF GÖRÜNTÜLEYICI, E-KITAP OKUYUCU VE PDF DÜZENLEYICIYE BIRDEN SAHIP OLACAKSINIZ HEM DE AYNI ANDA. BASIT, ÜCRETSIZ VE HAFIF, GERÇEKTEN DENEMEYE DEĞER!👉👉👉ŞIMDI PDF OKUYUCUYU INDIRIN VE TÜM ÖZELLIKLERININ ÜCRETSIZ KEYFINI ÇIKARIN!*KULLANIŞLI PDF GÖRÜNTÜLEYICI*👏 SAYFA SAYFA VE SÜREKLI KAYDIRMA MODU👏 YATAY VE DIKEY GÖRÜNTÜLEME MODU👏 DOĞRUDAN ISTEDIĞINIZ SAYFAYA GIDIN👏 PDF'DE METIN ARAYIN VE KOLAYCA KOPYALAYIN👏 SAYFALARI YAKINLAŞTIRIN VE UZAKLAŞTIRIN*ÜCRETSIZ OKUYUCU UYGULAMASI*✨TELEFONUNUZDAKI TÜM PDF DOSYALARINI OTOMATIK TARAMA VE BULMA✨ DOSYALARI VE METINLERI ANAHTAR KELIMELERLE HIZLI ARAMA✨ PDF DOSYALARINI BASIT BIR LISTEDE GÖSTERME✨ BELGELERI HIZLI AÇIN VE GÖRÜNTÜLEYIN✨ PDF SAYFALARINI IŞARETLEYIN*PRATIK PDF DÜZENLEYICI*✒️ PARAGRAFLARI VURGULAMA RENKLERI ILE IŞARETLEYIN✒️ ALT ÇIZGILI, ÜST ÇIZGILI NOTLAR ALIN ✒️ PDF DOSYALARINA E-IMZA EKLEYIN, PDF FORMLARINI DOLDURUN (YAKINDA)✒️ PDF DOSYALARINDA KARALAMA YAPIN✒️ PDF DOSYALARINA EK AÇIKLAMA EKLEYIN✒️ PDF DOSYASINDAKI HERHANGI BIR METNI KOLAYCA KOPYALAYINGÜÇLÜ PDF YÖNETICISI*✨SIKIŞTIRMA - İHTIYAÇLARINIZA UYGUN ŞEKILDE BOYUTLARINI AZALTMAK IÇIN PDF DOSYALARINI SIKIŞTIRIN. (YAKINDA)📅SON ERIŞILENLER - SON AÇILAN TÜM DOSYALAR HIZLI REFERANSINIZ IÇIN SIRALI OLARAK GÖRÜNTÜLENIR.🔒KILITLEME - PDF DOSYALARINI KILITLEMEK VE MERAKLI GÖZLERDEN KORUMAK IÇIN PAROLA BELIRLEYIN. 💡SILME/YENIDEN ADLANDIRMA/SIK KULLANILANLAR - DOSYALARI YENIDEN ADLANDIRABILIR, SILEBILIR VE SIK KULLANILANLARA EKLEYEBILIRSINIZ.🤝PAYLAŞIM - DOSYALARI BAŞKALARIYLA PAYLAŞIN VE RAHATÇA IŞBIRLIĞI YAPIN.🖨️YAZDIRMA - PDF DOSYALARINI TELEFONUNUZDAN HIZLI YAZDIRIN.#YAKINDA GELECEK ÖZELLIKLER#✔ PDF FORMLARI DOLDURMA✔ PDF DOSYALARINA E-IMZA EKLEME✔ KARANLIK MOD✔ PDF DOSYALARINI BÖLME VE BIRLEŞTIRME✔ PDF SAYFALARINI DÖNDÜRME✔ SAYFA EKLEME VEYA SILME✔ PDF VE WORD, EXCEL, JPG, PNG VB ARASINDA HIZLI DÖNÜŞTÜRME✔ AKILLI PDF TARAYICI HIZLI TARAMA VE PDF'LERI DÖNÜŞTÜRME...UYGULAMAYI OPTIMIZE ETMEK VE KULLANICI DENEYIMINI IYILEŞTIRMEK IÇIN ÇOK ÇALIŞMAYA DEVAM EDECEĞIZ. SORULARINIZ VARSA, LÜTFEN PDFREADERFEEDBACK@GMAIL.COM ADRESINDEN BIZIMLE ILETIŞIME GEÇMEKTEN ÇEKINMEYIN.PDF OKUYUCUGÜÇLÜ BIR PDF OKUYUCU MI ARIYORSUNUZ? PDF DOSYALARINA AÇIKLAMA EKLENEBILIR, TARANABILIR VE PDF OKUYUCU ILE GÖNDERILEBILIR. BU UYGULAMA TAM OLARAK IHTIYACINIZ OLAN ŞEY!PDF GÖRÜNTÜLEYICIPDF GÖRÜNTÜLEYICI AYNI ZAMANDA GÜÇLÜ BIR PDF OKUYUCUDUR. TEK BIR TIKLAMAYLA, PDF GÖRÜNTÜLEYICI IŞ VERIMLILIĞINIZI ARTIRMANIZI KOLAYLAŞTIRIR! PDF'LERINIZI DÜZENLEMEK IÇIN UYGULAMAYI ŞIMDI DENEYIN!PDF READERTAM ÖZELLIKLI PDF READER ISTER IŞTE ISTER EĞITIMDE OLSUN GEREKLIDIR. BUNU DENEYIN PDF READER PDF DOSYALARINIZI KOLAYCA YÖNETMENIZE VE DÜZENLEMENIZE YARDIMCI OLMASI IÇIN.PDF VIEWERPDF VIEWER PROFESYONEL BIR UYGULAMADIR. HIZLI, KULLANIMI KOLAY VE GÜÇLÜDÜR. PDF VIEWER ZEKICE ÇALIŞMANIZI SAĞLAR.</div>
            </Grid>
          </div>
      </div>
    </motion.nav>
  )
}
